
/****** Object:  Table [dbo].[Admin]    Script Date: 6/29/2023 7:55:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Admin](
	[AdminID] [int] NOT NULL,
	[Password] [text] NOT NULL,
 CONSTRAINT [PK_ADMIN] PRIMARY KEY CLUSTERED 
(
	[AdminID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Book]    Script Date: 6/29/2023 7:55:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Book](
	[SubjectId] [int] NOT NULL,
	[BookName] [nvarchar](max) NOT NULL,
	[BookID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_BOOK] PRIMARY KEY CLUSTERED 
(
	[BookID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Book_Topic]    Script Date: 6/29/2023 7:55:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Book_Topic](
	[BookId] [int] NOT NULL,
	[TopicId] [int] NOT NULL,
 CONSTRAINT [PK_BOOK_TOPIC] PRIMARY KEY CLUSTERED 
(
	[BookId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MCQs]    Script Date: 6/29/2023 7:55:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MCQs](
	[MCQID] [int] IDENTITY(1,1) NOT NULL,
	[Content] [nvarchar](max) NOT NULL,
	[Difficulty] [int] NOT NULL,
	[ChapterID] [int] NOT NULL,
	[SubjectID] [int] NOT NULL,
	[OptionA] [nvarchar](max) NOT NULL,
	[OptionB] [nvarchar](max) NOT NULL,
	[OptionC] [nvarchar](max) NOT NULL,
	[OptionD] [nvarchar](max) NOT NULL,
	[Answer] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_MCQS] PRIMARY KEY CLUSTERED 
(
	[MCQID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Paper_MCQ]    Script Date: 6/29/2023 7:55:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Paper_MCQ](
	[PaperID] [int] NOT NULL,
	[MCQID] [int] NOT NULL,
 CONSTRAINT [PK_PAPER_MCQ] PRIMARY KEY CLUSTERED 
(
	[PaperID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Paper_Question]    Script Date: 6/29/2023 7:55:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Paper_Question](
	[PaperID] [int] NOT NULL,
	[QuestionID] [int] NOT NULL,
 CONSTRAINT [PK_PAPER_QUESTION] PRIMARY KEY CLUSTERED 
(
	[PaperID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Past_Papers]    Script Date: 6/29/2023 7:55:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Past_Papers](
	[PaperID] [int] IDENTITY(1,1) NOT NULL,
	[Date] [date] NOT NULL,
 CONSTRAINT [PK_PAST_PAPERS] PRIMARY KEY CLUSTERED 
(
	[PaperID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Questions]    Script Date: 6/29/2023 7:55:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Questions](
	[QuestionID] [int] IDENTITY(1,1) NOT NULL,
	[TopicID] [int] NOT NULL,
	[SubjectID] [int] NOT NULL,
	[Difficulty] [int] NOT NULL,
	[Type] [nvarchar](max) NOT NULL,
	[Content] [nvarchar](max) NOT NULL,
	[Diagram] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_QUESTIONS] PRIMARY KEY CLUSTERED 
(
	[QuestionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Subject]    Script Date: 6/29/2023 7:55:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Subject](
	[SubjectId] [int] IDENTITY(1,1) NOT NULL,
	[SubjectName] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_SUBJECT] PRIMARY KEY CLUSTERED 
(
	[SubjectId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Topic]    Script Date: 6/29/2023 7:55:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Topic](
	[TopicId] [int] IDENTITY(1,1) NOT NULL,
	[TopicName] [nvarchar](max) NOT NULL,
	[ShortQs_Weightage] [float] NOT NULL,
	[LongQs_Weightage] [float] NOT NULL,
	[MCQs_Weightage] [float] NOT NULL,
 CONSTRAINT [PK_TOPIC] PRIMARY KEY CLUSTERED 
(
	[TopicId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Book]  WITH CHECK ADD  CONSTRAINT [Book_fk0] FOREIGN KEY([SubjectId])
REFERENCES [dbo].[Subject] ([SubjectId])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Book] CHECK CONSTRAINT [Book_fk0]
GO
ALTER TABLE [dbo].[Book_Topic]  WITH CHECK ADD  CONSTRAINT [Book_Topic_fk0] FOREIGN KEY([BookId])
REFERENCES [dbo].[Book] ([BookID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Book_Topic] CHECK CONSTRAINT [Book_Topic_fk0]
GO
ALTER TABLE [dbo].[Book_Topic]  WITH CHECK ADD  CONSTRAINT [Book_Topic_fk1] FOREIGN KEY([TopicId])
REFERENCES [dbo].[Topic] ([TopicId])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Book_Topic] CHECK CONSTRAINT [Book_Topic_fk1]
GO
ALTER TABLE [dbo].[Paper_MCQ]  WITH CHECK ADD  CONSTRAINT [Paper_MCQ_fk0] FOREIGN KEY([PaperID])
REFERENCES [dbo].[Past_Papers] ([PaperID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Paper_MCQ] CHECK CONSTRAINT [Paper_MCQ_fk0]
GO
ALTER TABLE [dbo].[Paper_MCQ]  WITH CHECK ADD  CONSTRAINT [Paper_MCQ_fk1] FOREIGN KEY([MCQID])
REFERENCES [dbo].[MCQs] ([MCQID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Paper_MCQ] CHECK CONSTRAINT [Paper_MCQ_fk1]
GO
ALTER TABLE [dbo].[Paper_Question]  WITH CHECK ADD  CONSTRAINT [Paper_Question_fk0] FOREIGN KEY([PaperID])
REFERENCES [dbo].[Past_Papers] ([PaperID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Paper_Question] CHECK CONSTRAINT [Paper_Question_fk0]
GO
ALTER TABLE [dbo].[Paper_Question]  WITH CHECK ADD  CONSTRAINT [Paper_Question_fk1] FOREIGN KEY([QuestionID])
REFERENCES [dbo].[Questions] ([QuestionID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Paper_Question] CHECK CONSTRAINT [Paper_Question_fk1]
GO
ALTER TABLE [dbo].[Questions]  WITH CHECK ADD  CONSTRAINT [Questions_fk0] FOREIGN KEY([TopicID])
REFERENCES [dbo].[Topic] ([TopicId])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Questions] CHECK CONSTRAINT [Questions_fk0]
GO
ALTER TABLE [dbo].[Questions]  WITH CHECK ADD  CONSTRAINT [Questions_fk1] FOREIGN KEY([SubjectID])
REFERENCES [dbo].[Subject] ([SubjectId])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Questions] CHECK CONSTRAINT [Questions_fk1]
GO
/****** Object:  StoredProcedure [dbo].[insert_subject]    Script Date: 6/29/2023 7:55:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[insert_subject] @subject_name text
AS 
BEGIN
	INSERT INTO Subject (SubjectName)
	VALUES (@subject_name);
END




--CREATE PROCEDURE insert_question 
--AS 
--insert 
GO
USE [master]
GO
ALTER DATABASE [khidmat_test] SET  READ_WRITE 
GO
